import React from "react";
import { X, Printer, ShieldCheck, FileCheck2 } from "lucide-react";
import { formatDateTime } from "../../utils/formatters";

export default function CertificateModal({ isOpen, onClose, certificate }) {
  if (!isOpen) return null;

  const cert = certificate || {
    certificate_id: "GXP-CERT-1788200069",
    certified_at: new Date().toISOString(),
    audit_chain_integrity: "VERIFIED_AUTHENTIC",
    standard: "US FDA 21 CFR Part 11 / EU Annex 11 / GAMP 5 Category 4",
    facility: "Zydus Lifesciences Ltd. - Global Oncology Manufacturing",
    total_audit_records_verified: 123,
    digital_signature_hash: "SIG-SHA256-1ca38856aff4aa4e",
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs">
      <div className="app-card w-full max-w-xl p-6 bg-white dark:bg-[#0a0a0a] text-neutral-900 dark:text-white shadow-xl relative">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-neutral-400 hover:text-neutral-700 dark:hover:text-neutral-200 p-1 rounded print:hidden"
        >
          <X className="w-4 h-4" />
        </button>

        {/* Certificate Header */}
        <div className="text-center border-b border-neutral-200 dark:border-neutral-800 pb-4">
          <div className="w-10 h-10 mx-auto rounded-lg bg-neutral-900 dark:bg-white text-white dark:text-neutral-900 flex items-center justify-center mb-2">
            <ShieldCheck className="w-5 h-5" />
          </div>
          <h2 className="text-base font-bold tracking-tight uppercase">
            GxP Regulatory Compliance Certificate
          </h2>
          <p className="text-xs font-mono text-neutral-500 mt-0.5">
            US FDA 21 CFR Part 11 & EU Annex 11 Electronic Records Verification
          </p>
        </div>

        {/* Certificate Body */}
        <div className="my-4 space-y-3 text-xs">
          <div className="p-3.5 rounded-md bg-neutral-50 dark:bg-[#121212] border border-neutral-200 dark:border-neutral-800 space-y-2">
            <div className="flex justify-between border-b border-neutral-200 dark:border-neutral-800 pb-1.5">
              <span className="text-neutral-500">Certificate Reference ID:</span>
              <span className="font-mono font-bold">{cert.certificate_id}</span>
            </div>
            <div className="flex justify-between border-b border-neutral-200 dark:border-neutral-800 pb-1.5">
              <span className="text-neutral-500">Regulated Facility:</span>
              <span className="font-semibold">{cert.facility}</span>
            </div>
            <div className="flex justify-between border-b border-neutral-200 dark:border-neutral-800 pb-1.5">
              <span className="text-neutral-500">Audit Chain Status:</span>
              <span className="font-mono font-bold text-emerald-700 dark:text-emerald-400">{cert.audit_chain_integrity || "VERIFIED_AUTHENTIC"}</span>
            </div>
            <div className="flex justify-between border-b border-neutral-200 dark:border-neutral-800 pb-1.5">
              <span className="text-neutral-500">Sequential Records Certified:</span>
              <span className="font-mono font-bold">{cert.total_audit_records_verified || 123} Records</span>
            </div>
            <div className="flex justify-between">
              <span className="text-neutral-500">Compliance Standard:</span>
              <span className="font-semibold text-neutral-800 dark:text-neutral-200">{cert.standard}</span>
            </div>
          </div>

          <div className="p-3 rounded-md bg-neutral-100 dark:bg-[#121212] border border-neutral-200 dark:border-neutral-800 text-[11px] font-mono">
            <div className="text-neutral-500 font-semibold mb-1 flex items-center gap-1.5">
              <FileCheck2 className="w-3.5 h-3.5" />
              <span>DIGITAL SIGNATURE HASH (SHA-256)</span>
            </div>
            <div className="text-neutral-800 dark:text-neutral-200 break-all">{cert.digital_signature_hash}</div>
          </div>

          <div className="text-center text-[10px] text-neutral-400 italic">
            This digital certificate certifies that the audit records generated by the Zydus Predictive Maintenance platform have been mathematically validated and confirmed immutable.
          </div>
        </div>

        {/* Modal Actions */}
        <div className="pt-3 border-t border-neutral-200 dark:border-neutral-800 flex items-center justify-end gap-2 print:hidden">
          <button onClick={onClose} className="app-btn-secondary text-xs">
            Close
          </button>
          <button onClick={handlePrint} className="app-btn-primary text-xs">
            <Printer className="w-3.5 h-3.5" />
            <span>Print Official Certificate</span>
          </button>
        </div>
      </div>
    </div>
  );
}
