apiVersion: v1
kind: ConfigMap
metadata:
  name: zydus-pm-config
  namespace: zydus-pm
data:
  DATABASE_HOST: "timescaledb.zydus-pm.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "zydus_pm"
  REDIS_URL: "redis://redis.zydus-pm.svc.cluster.local:6379/0"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.zydus-pm.svc.cluster.local:9092"
  KAFKA_TOPIC_SENSORS: "equipment.sensors.raw"
  KAFKA_TOPIC_ALERTS: "equipment.alerts"
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  ENABLE_PROMETHEUS_METRICS: "true"
