apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zydus-pm-ingress
  namespace: zydus-pm
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "zydus-backend"
spec:
  tls:
    - hosts:
        - pm.zyduslifesciences.com
      secretName: zydus-pm-tls-secret
  rules:
    - host: pm.zyduslifesciences.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: zydus-backend
                port:
                  number: 8000
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: zydus-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zydus-frontend
                port:
                  number: 80
