apiVersion: v1
kind: Secret
metadata:
  name: zydus-pm-secrets
  namespace: zydus-pm
type: Opaque
stringData:
  DATABASE_USER: "zydus_admin"
  DATABASE_PASSWORD: "ZydusProductionSecurePassword2026!"
  JWT_SECRET: "zydus_gxp_super_secure_sha256_cryptographic_jwt_key_2026_prod"
